GET http://localhost:3000/api/posts

POST http://localhost:3000/api/posts
Content-Type: application/json; charset=utf-8

{
    "title": "title",
    "content": "content"
}

PUT http://localhost:3000/api/posts/5922f6898f8ebaea6cd54312
Content-Type: application/json; charset=utf-8

{
    "title": "title update",
    "content": "content"
}

GET http://localhost:3000/api/posts/5922f6898f8ebaea6cd54312
